[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BrainFlow = "abd5acf9-0fc9-4730-984d-e27a37823580"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
